"""New Entity User

Revision ID: b3e2e19c8b5a
Revises: 
Create Date: 2022-11-08 23:18:35.192319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e2e19c8b5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('phone_number', sa.String(length=64), nullable=False),
    sa.Column('phone_country_code', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('phone_number', 'phone_country_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
