"""new table event

Revision ID: e63d015eb979
Revises: a156ff5f2728
Create Date: 2022-11-21 22:21:56.199213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63d015eb979'
down_revision = 'a156ff5f2728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.String(length=128), nullable=False),
    sa.Column('organizer_user_id', sa.Integer(), nullable=True),
    sa.Column('event_desc', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('key_for_attendee', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['organizer_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
